question_data = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Great Wall of China is visible from the moon.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Video streaming website YouTube was purchased in it's entirety by Facebook for "
                              "US$1.65 billion in stock.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "'Typewriter' is the longest word that can be typed using only the first row on a "
                              "QWERTY keyboard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Coca-Cola's original colour was green.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "French is an official language in Canada.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "question": "This is the correct spelling of 'Supercalifragilisticexpialidocious'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "It is automatically considered entrapment in the United States if the police sell you "
                              "illegal substances without revealing themselves.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "There are 86400 seconds in a day.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The word 'news' originates from the first letters of the 4 main directions "
                              "on a compass (North, East, West, South).",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The bikini is named after the 'Bikini Atoll', an island where the United "
                              "States conducted tests on atomic bombs.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of "
                              "urine.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Bulls are attracted to the color red.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "question": "'Number 16 Bus Shelter' was a child's name that was approved by the New Zealand "
                              "government.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "'Ananas'; is mostly used as the word for Pineapple in other languages.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Sun rises from the North.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The term 'Spam' came before the food product 'Spam'.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Sitting for more than three hours a day can cut two years off a person's life "
                              "expectancy.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The French word to travel is 'Travail'", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Pluto is a planet.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "When you cry in space, your tears stick to your face.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "One of Donald Trump's 2016 Presidential Campaign promises was to build a border "
                              "wall between the United States and Mexico.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Romanian belongs to the Romance language family, shared with French, Spanish, "
                              "Portuguese and Italian. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Albert Einstein had trouble with mathematics when he was in school.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "question": "Stagecoach owned 'South West Trains' before losing the rights to FirstGroup and MTR in "
                              "March of 2017.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "'Santa Claus' is a variety of melon.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "'27 Club' is a term used to refer to a list of famous actors, musicians, "
                              "and artists who died at the age of 27.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 "
                              "inside swimming pools and drinking water.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Scotland voted to become an independent country during the referendum from September "
                              "2014.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                  "question": "Spoon theory is a theory, utilizing 'Spoons' as a metaphor for energy they can use in "
                              "a day.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The scientific name for the Southern Lights is Aurora Australis?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The National Animal of Scotland is the Unicorn.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve "
                              "meat by stuffing a chicken with snow.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The British organisation CAMRA stands for The Campaign for Real Ale.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "The pickled gherkin was first added to hamburgers because a US health law required all "
                              "fast-food to include a source of Vitamin C.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Vietnam's national flag is a red star in front of a yellow background.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                  "question": "'Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.' is a grammatically "
                              "correct sentence.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Slovakia is a member of European Union-", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
